version: '3.8'

services:
  db:
    image: postgres:17.0-alpine3.20
    container_name: postgres_db
    environment:
      POSTGRES_USER: employee_user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: employee_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "employee_user"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
    container_name: go_backend
    depends_on:
      db:
        condition: service_healthy  # health check condition
    ports:
      - "8080:8080"
    environment:
      DB_HOST: db
      DB_USER: employee_user
      DB_PASSWORD: password
      DB_NAME: employee_db
      DB_PORT: 5432
      ALLOWED_ORIGINS: http://localhost:3000

  frontend:
    build:
      context: ./frontend
      args:
        REACT_APP_SERVER_URL: "http://localhost:8080/employees"
    container_name: react_frontend
    depends_on:
      - backend
    ports:
      - "3000:3000"

volumes:
  postgres_data:
