apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "frontend.fullname" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "frontend.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "frontend.name" . }}
    spec:
      imagePullSecrets:
        - name: frontsec1
      containers:
        - name: frontend
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.targetPort }}
          env:
            - name: REACT_APP_SERVER_URL
              value: {{ .Values.env.REACT_APP_SERVER_URL }}
          volumeMounts:
            - name: env-config
              mountPath: /app/.env
              subPath: .env
      volumes:
        - name: env-config
          configMap:
            name: {{ include "frontend.fullname" . }}-config
